### PR TITLE
Log ratchet keys in `olm::Session::debug`

### LINKED ISSUE #125: Log the sending chain ratchet key
To build a graph of DH steps we would need to have the ratchet key for the sending chain as well as the receiving chains. That way we'll be able to deduce the sending chain's parent.

More concretely the parent ratchet key of the currently active sending chain would have been the ratchet key kept in the inactive sender chain.

https://github.com/matrix-org/vodozemac/blob/8d0e0f704adeaeacd1cfd66c59ca319e3f1fe016/src/olm/session/double_ratchet.rs#L136-L140

### PR DESCRIPTION
**Pull request by richvdh**
Include the latest public ratchet keys in the debug output.

Fixes #125. Review commit-by-commit.

Question: does any of this need to be behind a feature flag? It's all public data so it feels like it's not a problem to retain or log it, but in theory I suppose there's a reduction in security due to keeping the parent ratchet key around.

### CODE REVIEW

**Review by poljar — CHANGES_REQUESTED** [review]
Left a small nit, looking good otherwise.

**Review by poljar — APPROVED** [review]

**Comment by poljar** [comment]
Do you want to squash that `fixup` commit?

**Comment by richvdh** [comment]
yarp, hold on

**Comment by poljar** [comment]
Ah, now we won't have a changelog entry, I wanted to write a merge commit containing one. :cry:

**Comment by richvdh** [comment]
Oh, sorry!

**Pull request merged**
